name: Secure Pipeline

on:
  pull_request:
    branches: [ 'main', 'dev' ]
  schedule:
    - cron: "0 0 * * 0"  # Weekly SAST scan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Upgrade setuptools to a secure version
      - name: Upgrade setuptools
        run: |
          pip install --upgrade setuptools

      # Install dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run unit tests
      - name: Run tests
        run: |
          python -m unittest discover

      # Run SAST scan using CodeQL
      - name: Run CodeQL analysis
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2

      # Check for vulnerable dependencies using pip-audit
      - name: Audit dependencies
        run: |
          pip install pip-audit
          pip-audit

      - name: Detect secrets in main.py
        run: |
          pip install truffleHog
          trufflehog . --max_depth 10 --json --include_paths main.py


      # Upload the results of truffleHog as artifacts
      - name: Upload truffleHog output
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-results
          path: trufflehog_output.json
