name: Secure Pipeline

on:
  pull_request:
    branches: [ 'main', 'dev' ]
  schedule:
    - cron: "0 0 * * 0"  # Weekly SAST scan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Upgrade setuptools to a secure version
      - name: Upgrade setuptools
        run: |
          pip install --upgrade setuptools

      # Install dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run unit tests
      - name: Run tests
        run: |
          python -m unittest discover

      # Run SAST scan using CodeQL
      - name: Run CodeQL analysis
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2

      # Check for vulnerable dependencies using pip-audit
      - name: Audit dependencies
        run: |
          pip install pip-audit
          pip-audit

      # Run TruffleHog scan for secrets detection
      - name: Scan secrets with TruffleHog
        uses: edplato/trufflehog-actions-scan@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
